version: "3.9"
services: 

  # Weather-service
  weather-service:
    build: ./weather-service
    ports: 
      - 5000:5000
    networks:
      - app-network
        
  # Window-door
  window-door:
    build: ./sensor-service/window-door
    ports: 
      - 4000:4000
      - 3000
    networks:
      - app-network
        
  # HeatPump-service
  heatpump-service:
    build: ./sensor-service/heat-pump
    ports: 
      - 4002:4000
      - 3000
    networks:
      - app-network
        
  # thermometer-service
  thermometer-service:
    build: ./sensor-service/thermometer
    ports: 
      - 4004:4000
      - 3000
    networks:
      - app-network
          
  # Actuator-service
  actuator-service:
    build: ./actuator-service
    ports: 
      - 3000:3000
    depends_on:           
      window-door:
        condition: service_started  
      heatpump-service:
        condition: service_started  
    networks:
      - app-network
      
  # Backend
  backend-server:
    build: ./backend
    ports: 
      - 8000:8000
      - 7000
    depends_on:
      actuator-service:
        condition: service_started   
      weather-service:
        condition: service_started        
      window-door:
        condition: service_started  
      heatpump-service:
        condition: service_started  
    networks:
      app-network:
        #bind to apache proxy pass
        ipv4_address: "10.88.0.11"
        
  # Frontend
  web-app:
    build: ./frontend
    ports: 
      - 8080:80
    depends_on:
      backend-server:
        condition: service_started  
    networks:
      - app-network

networks:
  app-network:    
      name: app-network
      driver: bridge
      ipam:
        config:
          - subnet: "10.88.0.0/16"
